### PR TITLE
Fixed the warning generated by Swift 2.2

### PR DESCRIPTION
**Pull request by SudeepSidhu**
I only bumped the minor version of the pod, but given that the changes are breaking for anyone < Swift 2.2 we can bump the major version to cover anyone who hasn't migrated to 2.2 yet.

### CODE REVIEW

**Comment by nickvelloff** [comment]
👍 possible to merge?

**Comment by Adlai-Holler** [comment]
Sorry for the delay here, I initially put off responding because Xcode 7.3.1 is a disaster but hopefully Apple will fix it before I want to add any new features. Thanks @SudeepSidhu!

**Comment by nickvelloff** [comment]
Thanks @Adlai-Holler! Someone from Facebook engineering team recommended this, and I see bits of it in the ASDK code base. Really slick thanks.

**Comment by Adlai-Holler** [comment]
@nickvelloff Glad you like it, hope it serves you well!

**Pull request merged**
